version: '3.9'

services:
  nginx:
    build: ./nginx
    image: registry.hosted-domains.com/shane/plexstack-nginx:${VERSION}
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.STACK_NAME-http.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.STACK_NAME-http.entrypoints=http"
        - "traefik.http.routers.STACK_NAME-http.middlewares=https-redirect"
        - "traefik.http.routers.STACK_NAME-https.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.STACK_NAME-https.entrypoints=https"
        - "traefik.http.routers.STACK_NAME-https.tls=true"
        - "traefik.http.routers.STACK_NAME-https.tls.certresolver=le"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.port=80"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.scheme=http"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - download_dir:/data/media
      - media_dir:/data/downloads
#    secrets:
#      - source: cssnr.com.crt
#        target: /etc/ssl/cssnr.com.crt
#      - source: cssnr.com.key
#        target: /etc/ssl/cssnr.com.key
#      - source: cssnr_basic_http_auth
#        target: /etc/nginx/auth.users
    depends_on:
      - plex
      - qbittorrent
    networks:
      - traefik-public
      - internal-net
#    ports:
#      - "${PLEX_PORT}:32400"

  plex:
    image: plexinc/pms-docker:latest
    hostname: ${TRAEFIK_HOST}
    deploy:
      replicas: 1
#      labels:
#        - "traefik.enable=true"
#        - "traefik.docker.network=traefik-public"
#        - "traefik.constraint-label=traefik-public"
#        - "traefik.http.routers.STACK_NAME-plex.entrypoints=http"
#        - "traefik.http.routers.STACK_NAME-plex.entrypoints.address=:${PLEX_PORT}"
#        - "traefik.http.services.STACK_NAME.loadbalancer.server.port=${PLEX_PORT}"
#        - "traefik.http.services.STACK_NAME.loadbalancer.server.scheme=http"
      resources:
        limits:
          cpus: '2'
          memory: 1gb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - VERSION=docker
      - ADVERTISE_IP=https://${TRAEFIK_HOST}:443
    volumes:
      - plex_dir:/config
      - media_dir:/media
    networks:
      - traefik-public
      - internal-net
#    ports:
#      - "${PLEX_PORT}:32400"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - qbit_dir:/config
      - media_dir:/media
      - download_dir:/downloads
    networks:
      - internal-net
    ports:
      - "${QBIT_PORT}:6881"
      - "${QBIT_PORT}:6881/udp"

#secrets:
#  cssnr.com.crt:
#    external: true
#  cssnr.com.key:
#    external: true
#  cssnr_basic_http_auth:
#    external: true

volumes:
  download_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}/download"
  plex_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}/plex"
  qbit_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}/qbittorrent"
  media_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}/media"

networks:
  traefik-public:
    external: true
  internal-net:
    driver: overlay
